name: Automated Dependency Updates

on:
  push:
    branches: [ canary ]

jobs:
  dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Tools
      id: tools
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Validate
      id: validate
      run: |
        OUTPUT=$(dotnet outdated)
        if [[ $OUTPUT =~ "No outdated dependencies were detected" ]]; then
            echo "::set-output name=needs_updates::false"
        else
            echo "::set-output name=needs_updates::true"
        fi
      shell: bash

    - name: Update
      id: update
      if: ${{ steps.validate.outputs.needs_updates == 'true' }}
      run: dotnet outdated -u

    - name: Test
      id: test
      if: ${{ steps.validate.outputs.needs_updates == 'true' }}
      run: dotnet test -c Release -v minimal

    - name: Push
      id: push
      if: ${{ steps.validate.outputs.needs_updates == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Dependency Updates
