name: Update Dependencies

on:
  push:
    branches: [ canary ]

jobs:
  dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Tools
      id: tools
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Validate
      id: validate
      run: |
        echo "::set-output name=outdated::$(dotnet outdated)\n"

    - name: Update
      id: update
      run: dotnet outdated -u

    - name: Test
      id: test
      run: dotnet test -c Release -v minimal
